services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=license-service'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=root'
    ports:
      - '5433:5432'
